## Import Libraries

In [1]:
import pandas as pd 
from selenium import webdriver
from bs4 import BeautifulSoup
import time

## Load Data

In [2]:
df = pd.read_csv("Skincare Dataset/pores_data.csv")
df = df.loc[:, ~df.columns.str.contains("^Unnamed: 0")]

df.head(10)

,problem,ingredient,product name,product link
0,pores,salicylic-acid,9.0% | Resist Bha 9\n \n\n P...,https://inkeedecoder.com/products/paulas-choic...
1,pores,salicylic-acid,6.0% | Compound Salicylic Acid Liniment\n ...,https://inkeedecoder.com/products/sanyi-compou...
2,pores,salicylic-acid,2.0% | Azelaic Acid Control Facial Acne Gel\n ...,https://inkeedecoder.com/products/aisuanis-emp...
3,pores,salicylic-acid,2.0% | Nuorishing Spa Mask\n \n\n ...,https://inkeedecoder.com/products/broda-r-pro-...
4,pores,salicylic-acid,2.0% | Flawless Neutralising Gel\n \n\n...,https://inkeedecoder.com/products/dr-sam-bunti...
5,pores,salicylic-acid,2.0% | Neem & BHA Spot Clarifying Serum\n ...,https://inkeedecoder.com/products/dr-sheths-ne...
6,pores,salicylic-acid,2.0% | Salicylic Acid 2% Serum\n \n\n ...,https://inkeedecoder.com/products/garden-of-wi...
7,pores,salicylic-acid,2.0% | Rapid Relief Acne Spot Treatment\n ...,https://inkeedecoder.com/products/murad-rapid-...
8,pores,salicylic-acid,2.0% | Clear Pore Oil-Eliminating Astringent\n...,https://inkeedecoder.com/products/neutrogena-c...
9,pores,salicylic-acid,2.0% | Clear Regular Strength Anti-Redness Exf...,https://inkeedecoder.com/products/paulas-choic...

##### Membuat Driver untuk Chrome Browser

In [3]:
driver = webdriver.Chrome()

##### Scraping Data

In [4]:
for index, row in df.iterrows():
    url = row["product link"]

    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    ingredient_elements = soup.select("a.ingred-link")

    ingredients = []

    for ing in ingredient_elements:
        ingredient_name = ing.get_text(strip=True)

        if ingredient_name not in ingredients:
            ingredients.append(ingredient_name)

    if len(ingredients) > 0:
        df.loc[index, "ingredient"] = ", ".join(ingredients)

    print("Product:", row["product name"])
    print("Link:", url)
    print("Jumlah ingredient:", len(ingredients))
    print("Ingredient:", ingredients)
    print("-" * 50)
    
driver.quit()

Product: 9.0% | Resist Bha 9


            Paula's Choice
Link: https://inkeedecoder.com/products/paulas-choice-resist-bha-9
Jumlah ingredient: 13
Ingredient: ['Propylene Glycol', 'PEG-75', 'PEG-8', 'Water', 'Salicylic Acid 9.0%', 'Glycerin', 'Avena Sativa (Oat) Kernel Extract', 'Butylene Glycol', 'Boerhavia Diffusa Root Extract', 'Sea Whip Extract', 'Arginine', 'Polysorbate 20', 'Disodium EDTA']
--------------------------------------------------
Product: 6.0% | Compound Salicylic Acid Liniment


            Sanyi
Link: https://inkeedecoder.com/products/sanyi-compound-salicylic-acid-liniment
Jumlah ingredient: 7
Ingredient: ['Salicylic Acid 6.0%', 'Resorcinol 2.0%', 'Phenol 1.0%', 'Methyl Salicylate 0.003%', 'Glycerin 0.003%', 'Alcohol', 'Water']
--------------------------------------------------
Product: 2.0% | Azelaic Acid Control Facial Acne Gel


            Aisuanis
Link: https://inkeedecoder.com/products/aisuanis-empowerment-azelaic-acid-control-facial-acne-gel
Jumlah ingredient: 17
Ingredient: ['Aqua', 'Propylene Glycol', 'Azelaic Acid 15.0%', 'Tetrahydroxypropyl Ethylenediamine', 'Potassium Azeloyl Diglycinate 5.0%', 'Polyacrylate Crosspolymer-6', 'Salicylic Acid 2.0%', 'Lactobionic Acid', 'Bisabolol', 'Gluconolactone', 'Arginine', 'Quaternium-73', 'Dipotassium Glycyrrhizate', '1,2-Hexanediol', 'Isopentyldiol', 'O- Cymen-5-Ol', 'Hydroxyacetophenone']
--------------------------------------------------
Product: 2.0% | Nuorishing Spa Mask


            BRODA® PRO
Link: https://inkeedecoder.com/products/broda-r-pro-nuorishing-spa-mask
Jumlah ingredient: 8
Ingredient: ['Water', 'Poloxamer 407', 'Laureth-40', 'PEG-8', 'Glycerin', 'Salicylic Acid 2.0%', 'Bisabolol', 'Dipotassium Glycyrrhizate']
--------------------------------------------------
Product: 2.0% | Flawless Neutralising Gel


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-neutralising-gel
Jumlah ingredient: 11
Ingredient: ['Aqua (Water)', 'Propylene Glycol', 'Ammonium Polyacryloyldimethyl Taurate', 'Azelaic Acid 5.0%', 'Squalane 5.0%', 'Salicylic Acid 2.0%', 'Glyceryl Stearate', 'Disodium EDTA', 'PEG-100 Stearate', 'Sodium Hydroxide', 'Bakuchiol 0.5%']
--------------------------------------------------
Product: 2.0% | Neem & BHA Spot Clarifying Serum


            Dr. Sheth's
Link: https://inkeedecoder.com/products/dr-sheths-neem-bha-spot-clarifying-serum
Jumlah ingredient: 18
Ingredient: ['Salicylic Acid 2.0%', 'Neem Oil (Anti-Bacterial)', 'Tea Tree Oil (Anti-Acne)', 'Niacinamide (Brightening, Anti-Redness)', 'Green Tea Extract (Conditioning, Calming)', '(Wheat And Oat) Sugar (Hydration - Gluten Free)', 'Allantoin (Healing)', 'Lavender Oil (Calming)', 'Glycerin (Humectant)', 'Propylene Glycol (Humectant, Penetration Enhancer)', 'Polyacrylate Crosspolymer - 6 (Co-Gelling Agent)', 'Acacia Senegal Gum (Gelling Agent)', 'Xanthan Gum (Gelling Agent)', 'Disodium EDTA (Heavy Metal Remover)', 'Sodium Hydroxide (Ph Adjuster)', 'Polysorbate 20 (Emulsifier)', 'Phenoxyethanol (Preservative)', '(Double Distilled And Demineralized) Water']
--------------------------------------------------
Product: 2.0% | Salicylic Acid 2% Serum


            Garden of Wisdom
Link: https://inkeedecoder.com/products/garden-of-wisdom-salicylic-acid-serum
Jumlah ingredient: 4
Ingredient: ['Propanediol', 'Spring Water', 'Salicylic Acid 2.0%', 'Dehydroxanthan Gum']
--------------------------------------------------
Product: 2.0% | Rapid Relief Acne Spot Treatment


            Murad
Link: https://inkeedecoder.com/products/murad-rapid-relief-acne-spot-treatment
Jumlah ingredient: 26
Ingredient: ['Salicylic Acid 2.0%', 'Water (Aqua)', 'Alcohol', 'Hamamelis Virginiana (Witch Hazel) Water', 'Propanediol', 'Pentylene Glycol', 'Glycerin', 'Silica', 'Butylene Glycol', 'Polyacrylate Crosspolymer-6', 'C12-15 Alkyl Lactate', 'Aesculus Hippocastanum (Horse Chestnut) Seed Extract', 'Avena Sativa (Oat) Kernel Extract', 'Urea', 'Yeast Amino Acids', 'Trehalose', 'Inositol', 'Taurine', 'Betaine', 'Thymol', 'Terpineol', 'Hydroxyphenyl Propamidobenzoic Acid', 'Shea Butter Ethyl Esters', '4-T-Butylcyclohexanol', 'Disodium EDTA', 'Sodium Hydroxide']
--------------------------------------------------
Product: 2.0% | Clear Pore Oil-Eliminating Astringent


            Neutrogena
Link: https://inkeedecoder.com/products/neutrogena-clear-pore-oil-eliminating-astringent
Jumlah ingredient: 14
Ingredient: ['Salicylic Acid 2.0%', 'Water', 'Alcohol Denat', 'Hamamelis Virginiana (Witch Hazel) Water', 'Butylene Glycol', 'Glycereth-7', 'Methyl Gluceth-20', 'Alcohol', 'Fragrance', 'Propylene Glycol', 'Benzophenone-4', 'Aloe Barbadensis Leaf Extract', 'Chamomilla Recutita (Matricaria) Flower Extract', 'Blue 1']
--------------------------------------------------
Product: 2.0% | Clear Regular Strength Anti-Redness Exfoliating Solution With 2% Salicylic Acid


            Paula's Choice
Link: https://inkeedecoder.com/products/paulas-choice-clear-regular-strength-anti-redness-exfoliating-solution-with-2-salicylic-acid
Jumlah ingredient: 18
Ingredient: ['Water (Aqua)', 'Dipropylene Glycol', 'Pentylene Glycol', 'Salicylic Acid 2.0%', 'Polysorbate 20', 'Butylene Glycol', 'Glycerin', 'Sodium Hyaluronate', 'Dipotassium Glycyrrhizate', 'Allantoin', 'Panthenol', 'PEG/\u200bPPG-17/\u200b6 Copolymer', 'Methyl Gluceth-20', 'Glycereth-26', 'Bis-PEG-18 Methyl Ether Dimethyl Silane', 'Sodium Hydroxide', 'Tetrasodium EDTA', 'Sodium Metabisulfite']
--------------------------------------------------
Product: 2.0% | Resist Daily Pore-Refining Treatment 2% Bha


            Paula's Choice
Link: https://inkeedecoder.com/products/paulas-choice-resist-daily-pore-refining-treatment-2-bha
Jumlah ingredient: 26
Ingredient: ['Water (Aqua)', 'Dipropylene Glycol', 'Salicylic Acid 2.0%', 'Pentylene Glycol', 'Butylene Glycol', 'Polysorbate 20', 'Palmitoyl Tripeptide-1', 'Palmitoyl Tetrapeptide-7', 'Dipotassium Glycyrrhizate', 'Nordihydroguaiaretic Acid', 'Oleanolic Acid', 'Sodium Hyaluronate', 'Allantoin', 'Trehalose', 'Panthenol', 'Glycerine', 'PEG-60 Almond Glycerides', 'Sodium Metabisulfite', 'PEG/\u200bPPG-17/\u200b6 Copolymer', 'Methyl Gluceth-20', 'Bis-PEG-18 Methyl Ether Dimethyl Silane', 'Glycereth-26', 'Sodium Hydroxide', 'Carbomer', 'Disodium EDTA', 'Caprylyl Glycol']
--------------------------------------------------
Product: 2.0% | Acne-Clear Oil-Free Matte Moisturizer


            Peter Thomas Roth
Link: https://inkeedecoder.com/products/peter-thomas-roth-acne-clear-oil-free-matte-moisturizer
Jumlah ingredient: 41
Ingredient: ['Salicylic Acid 2.0%', 'Water/\u200bAqua/\u200bEau', 'Dimethicone', 'Propanediol', 'Caprylic/\u200bCapric Triglyceride', 'Glycerin', 'Jojoba Esters', 'Isodecyl Neopentanoate', 'Cetearyl Alcohol', 'Panthenol', 'Polysilicone-11', 'Cordyceps Sinensis Extract', 'Trametes Versicolor (Mushroom) Extract', 'Helianthus Annuus (Sunflower) Seed Wax', 'Sodium Hydroxide', 'Hydroxyethyl Acrylate/\u200bSodium Acryloyldimethyl Taurate Copolymer', 'Polyacrylate Crosspolymer-6', 'Ceteareth-20', 'Isohexadecane', 'Tocopheryl Acetate', 'Hydrogenated Lecithin', 'Aloe Barbadensis Leaf Juice', 'Butylene Glycol', 'Allantoin', 'Disodium EDTA', 'Sodium Hyaluronate', 'Acacia Decurrens Flower Wax', 'Polyglycerin-3', 'Phenoxyethanol', 'Polysorbate 60', 'Sodium PCA', 'Sodium Citrate', 'Sorbitan Isostearate', 'Maclura Cochinchinensis Leaf Prenylflavonoids', 'T-Butyl Alcohol', 'Glycosaminoglycans', 'Potassium Sorbate', 'Sodium Benzoate', 'Ethylhexylglycerin', 'Citric Acid', 'Trisodium EDTA']
--------------------------------------------------
Product: Show all >>
Link: https://inkeedecoder.com/ingredients/salicylic-acid?koffset=1
Jumlah ingredient: 0
Ingredient: []
--------------------------------------------------
Product: 20.0% | Clinical Niacinamide 20% Treatment


            Paula's Choice
Link: https://inkeedecoder.com/products/paulas-choice-clinical-niacinamide-20-treatment
Jumlah ingredient: 25
Ingredient: ['Water (Aqua)', 'Niacinamide 20.0%', 'Pentylene Glycol (Solvent/\u200bTexture Enhancer)', 'Butylene Glycol (Slip Agent/\u200bHydration)', 'Glycerin (Skin-Replenishing)', 'Acetyl Glucosamine (Skin-Replenishing)', 'Ascorbyl Glucoside (Vitamin C/\u200bAntioxidant)', 'Glycyrrhiza Glabra (Licorice) Root Extract (Skinsoothing/\u200bAntioxidant)', 'Spiraea Ulmaria (Meadowsweet) Extract (Antioxidant)', 'Portulaca Oleracea (Purslane) Extract (Antioxidant)', 'Camellia Japonica Flower Extract (Antioxidant)', 'Epigallocatechin Gallate (Green Tea-Derived Antioxidant)', 'Boerhavia Diffusa Root Extract (Skin-Soothing)', 'Camellia Sinensis (Green Tea) Leaf Extract (Antioxidant)', 'Allantoin (Skinsoothing)', 'Lecithin (Skin-Replenishing)', 'Pullulan (Texture Enhancer)', 'Panthenol (Hydration)', 'Silica (Absorbent)', 'Xanthan Gum (Thickener)', 'Sclerotium Gum (Thickener)', 'Propanediol (Hydration)', 'Sodium Phytate (Chelating Agent)', 'Phenoxyethanol (Preservative)', 'Ethylhexylglycerin (Preservative)']
--------------------------------------------------
Product: 10.0% | Rejuvenating Brightening Essence


            BRODA® PRO
Link: https://inkeedecoder.com/products/broda-r-pro-rejuvenating-brightening-essence
Jumlah ingredient: 14
Ingredient: ['Water', 'Niacinamide 10.0%', 'Butylene Glycol', 'PEG-8', 'Propylene Glycol', 'Poloxamer 407', 'Tranexamic Acid 3.0%', 'Laureth-4', 'Salicylic Acid 1.0%', 'Carbomer', 'Dipotassium Glycyrrhizate', 'Bisabolol', 'Methylparaben', 'Phenoxyethanol']
--------------------------------------------------
Product: 10.0% | Niacinamide 10 Serum


            Cos De BAHA
Link: https://inkeedecoder.com/products/cos-de-baha-niacinamide-10-serum
Jumlah ingredient: 14
Ingredient: ['Organic Aloe Barbadensis Leaf Extract (Aloe)', 'Niacinamide 10.0%', 'Propanediol', 'Glycerin', '1,2-Hexanediol', 'Zinc Pca 1.0%', 'Sodium Hyaluronate', 'Allantoin', 'Dipotassium Glycyrrhizate', 'Organic Hamamelis Virginiana (Witch Hazel) Leaf Extract', 'Organic Rosmarinus Officinalis (Rosemary) Extract', 'Organic Eucalyptus Globulus (Eucalyptus) Leaf Extract', 'Organic Thymus Vulgaris (Thyme) Extract', 'Organic Aspalathus Linearis (Rooibos) Extract']
--------------------------------------------------
Product: 10.0% | Flawless Nightly Serum


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-nightly-serum
Jumlah ingredient: 20
Ingredient: ['Aqua (Water/\u200bEau)', 'Butylene Glycol', 'Niacinamide 10.0%', 'Azelaic Acid 5.0%', 'Dicaprylyl Carbonate', 'Glycerin', 'Ethoxydiglycol', 'Cetearyl Alcohol', 'Dimethyl Isosorbide', 'Bakuchiol 1.0%', 'Tapioca Starch', 'Benzyl Alcohol', 'Allantoin', 'Sodium Stearoyl Glutamate', 'Xanthan Gum', 'Phenoxyethanol', 'Hydroxypinacolone Retinoate 0.2%', 'Disodium EDTA', 'Dehydroacetic Acid', 'Polymethylsilsesquioxane']
--------------------------------------------------
Product: 10.0% | Niacinamide


            The Inkey List
Link: https://inkeedecoder.com/products/the-inkey-list-niacinamide
Jumlah ingredient: 23
Ingredient: ['Water (Aqua/\u200bEau)', 'Niacinamide 10.0%', 'Glycerin', 'Propanediol', 'Butylene Glycol', 'Squalane', 'Leuconostoc/\u200bRadish Root Ferment Filtrate', 'Hyaluronic Acid', 'Phenoxyethanol', 'Hydroxyethyl Acrylate/\u200bSodium Acryloyldimethyl Taurate Copolymer', 'Hydroxyethylcellulose', 'Phospholipids', 'Xanthan Gum', 'Glycine Soja (Soybean) Extract', 'Allantoin', 'Disodium EDTA', 'Polysorbate 60', 'Panthenol', 'Glycolipids', 'Glycine Soja (Soybean) Sterols', 'Disodium Phosphate', 'Citric Acid', 'Sodium Phosphate']
--------------------------------------------------
Product: 10.0% | Niacinamide 10% + Zinc 1%


            The Ordinary
Link: https://inkeedecoder.com/products/the-ordinary-niacinamide-10-zinc-1-serum1
Jumlah ingredient: 11
Ingredient: ['Aqua (Water)', 'Niacinamide 10.0%', 'Pentylene Glycol', 'Zinc Pca 1.0%', 'Dimethyl Isosorbide', 'Tamarindus Indica Seed Gum', 'Xanthan Gum', 'Isoceteth-20', 'Ethoxydiglycol', 'Phenoxyethanol', 'Chlorphenesin']
--------------------------------------------------
Product: 10.0% | Pore Refining & Spot Correcting Concentrate


            dermistry⁺
Link: https://inkeedecoder.com/products/dermistry-pore-refining-spot-correcting-concentrate
Jumlah ingredient: 19
Ingredient: ['Aqua', 'Niacinamide 10.0%', 'Methylpropanediol', 'Pentylene Glycol', 'Salicylic Acid 1.0%', '3-O-Ethyl Ascorbic Acid', 'Carnosine', 'Opuntia Streptacantha Stem Extract', 'Glycine Max (Soybean) Seed Extract', 'Rhamnose', 'Amylopectin', 'Dextrin', 'Xanthan Gum', 'Trehalose', 'Tapioca Starch', 'Glycerin', 'Citric Acid', 'Hydroxyethylcellulose', '1,2-Hexanediol']
--------------------------------------------------
Product: 5.0% | Star Light Spot Corrector


            Acaderma
Link: https://inkeedecoder.com/products/acaderma-star-light-spot-corrector
Jumlah ingredient: 33
Ingredient: ['Aqua (Water)', 'Niacinamide 5.0%', 'Tranexamic Acid 3.0%', 'PEG-11 Methyl Ether Dimethicone', 'Caprylyl Methicone', 'Caprylic/\u200bCapric Triglyceride', '1-Methylhydantoin-2-Imide', '1,2-Hexanediol', 'PEG-12 Dimethicone', 'Propanediol', 'PEG-12 Dimethicone/\u200bPPG-20 Crosspolymer', 'Tocopheryl Acetate', 'Morus Alba Root Extract', 'Brassica Campestris (Rapeseed) Seed Oil', 'Althaea Officinalis Root Extract', 'Glycyrrhiza Glabra (Licorice) Root Extract', 'Polyglyceryl-3 Diisostearate', 'Oryza Sativa (Rice) Bran Extract', 'Vaccinium Angustifolium (Blueberry) Fruit Extract', 'Panthenol', 'Allantoin', 'Sodium Hyaluronate', 'Phenoxyethanol', 'Aminomethyl Propanediol', 'Carbomer', 'Ethylhexylglycerin', 'Sodium Polyacrylate', 'Dimethicone', 'Cyclopentasiloxane', 'Glycerin', 'Trideceth-6', 'PEG/\u200bPPG-18/\u200b18 Dimethicone', 'Disodium EDTA']
--------------------------------------------------
Product: 5.0% | Flawless Brightly Serum


            Dr Sam Bunting
Link: https://inkeedecoder.com/products/dr-sam-bunting-flawless-brightly-serum
Jumlah ingredient: 18
Ingredient: ['Aqua (Water)', 'Azelaic Acid 10.0%', 'Caprylic/\u200bCapric Triglyceride', 'Niacinamide 5.0%', 'Dicaprylyl Carbonate', 'Ascorbyl Glucoside 2.0%', 'Cetearyl Alcohol', 'Glycerin', 'Glyceryl Stearate SE', 'Cetearyl Olivate', 'Bakuchiol 1.0%', 'Sorbitan Olivate', 'Benzyl Alcohol', 'Xanthan Gum', 'Phenoxyethanol', 'Sodium Hydroxide', 'Disodium EDTA', 'Dehydroacetic Acid']
--------------------------------------------------
Product: 5.0% | Flawless Moisturiser


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-moisturiser
Jumlah ingredient: 26
Ingredient: ['Aqua (Water/\u200bEau)', 'Butyrospermum Parkii (Shea) Butter', 'Cyclopentasiloxane', 'Niacinamide 5.0%', 'Propanediol', 'Dimethicone', 'Glycerin', 'Cetyl Alcohol', 'Caprylic/\u200bCapric Triglyceride', 'Glyceryl Stearate Se', 'Panthenol', 'Xylitylglucoside', 'Polysilicone-11', 'Stearic Acid', 'Anhydroxylitol', 'Phenoxyethanol', 'Carbomer', 'Allantoin', 'Sodium Hyaluronate', 'Xylitol', 'Sodium Hydroxymethylglycinate', 'Sodium Stearoyl Glutamate', 'Sodium Hydroxide', 'Disodium Edta', 'Ethylhexylglycerin', 'Citric Acid']
--------------------------------------------------
Product: 5.0% | Lab. Restoring Brightening Serum


            Purid
Link: https://inkeedecoder.com/products/purid-lab-restoring-brightening-serum
Jumlah ingredient: 17
Ingredient: ['Water', 'Niacinamide 5.0%', 'Arbutin 2.0%', 'Acetyl Glucosamine 2.0%', 'Bis-Ethoxydiglycol Cyclohexane 1,4-Dicarboxylate 1.0%', 'Pentylene Glycol', 'Butylene Glycol', 'Sophora Flavescens Root Extract**', 'Glycyrrhiza Inflata Root Extract**', 'Scutellaria Baicalensis Root Extract**', 'Dimethicone', 'Sodium Polyacrylate', 'C18-21 Alkane', 'Trideceth-6', '1,2-Hexanediol', 'Hydroxyacetophenone', 'Chlorphenesin']
--------------------------------------------------
Product: 5.0% | Abc Repair & Restore Antioxidant Serum Rx2


            RejuAus
Link: https://inkeedecoder.com/products/rejuaus-abc-repair-restore-antioxidant-serum-rx2
Jumlah ingredient: 58
Ingredient: ['Water', 'Aloe Vera Juice Extract', 'Niacinamide 5.0%', 'Cyclodextrin', 'Caprylic/\u200bCapric Triglyceride', 'Gluconolactone', 'Terminalia Ferdinandiana (Kakadu Plum) Fruit Extract 5.0%', 'Carnitine (L)', 'Vegetable Glycerin', 'Polysorbate 20', 'Retinaldehyd 0.5%', '(Symwhite) Phenylethyl Resorcinol', 'Tocopheryl Acetate (D-Alpha)', 'Bisabolol (L-Alpha)', 'Hydrolyzed Marine Collagen', 'Porphyra Umbilicalis (Red Algae) Extract', 'Vaccinium Macrocarpon (Cranberry) Fruit Extract', 'Lactic Acid', 'Rubus Chamaemorus Seed Oil', 'Citrus Aurantium Bergamia (Bergamot) Fruit Oil', 'Michelia Alba (Magnolia) Flower Oil', 'Maltodextrin', 'Sodium Lactate', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'Japonica (Honeysuckle) Flower Extract', 'Lecithin', 'Citrus Aurantium Dulcis (Orange) Fruit Extract', 'Jojoba Oil', 'Glycine Soja (Soybean) Oil', 'Apple Fruit Extract', 'Mangosteen Fruit Extract', 'Sorbitol', 'Beta-Glucan', 'Aloe Vera', 'Allantoin', 'Calendula Officinalis Flower Extract', 'Chamomile', 'Hyaluronic Acid', 'Hyaluronic Acid Hmw', 'Colloidal Oatmeal (Avena Sativa)', 'Canadian Willow Herb Extract', 'Coenzyme Q10', 'Butylene Glycol', 'Phenoxyethanol', 'Caprylyl Glycol', 'Ethylhexylglycerin', 'Pentylene Glycol', 'Potassium Sorbate', 'Green Tea Leaf Extract', 'Alcohol', 'Citric Acid', 'Xanthan Gum', 'Sclerotium Gum', 'Pullulan', 'Sodium Benzoate', 'Benzoic Acid', '1,2-Hexanediol', 'Sodium Phytate']
--------------------------------------------------
Product: Show all >>
Link: https://inkeedecoder.com/ingredients/niacinamide?koffset=1
Jumlah ingredient: 0
Ingredient: []
--------------------------------------------------
Product: 1.0% | A-Passioni Retinol Cream


            Drunk Elephant
Link: https://inkeedecoder.com/products/drunk-elephant-a-passioni-retinol-cream
Jumlah ingredient: 63
Ingredient: ['Water/\u200bAqua/\u200bEau', 'Glycerin', 'Coco-Caprylate', 'Stearic Acid', 'Coconut Alkanes', 'Glyceryl Stearate', 'Niacinamide', 'Caprylic/\u200bCapric Triglyceride', 'Cetearyl Alcohol', 'Pentylene Glycol', 'Passiflora Edulis Seed Oil', 'Retinol 1.0%', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'Sclerocarya Birrea Seed Oil', 'Prunus Armeniaca (Apricot) Kernel Oil', 'Cetyl Ethylhexanoate', 'Palmitoyl Tripeptide-1', 'Palmitoyl Tetrapeptide-7', 'Brassica Oleracea Acephala Leaf Extract', 'Brassica Oleracea Italica (Broccoli) Extract', 'Tetrahexyldecyl Ascorbate', 'Chrysin', 'Persea Gratissima (Avocado) Oil', 'Linoleic Acid', 'Linolenic Acid', 'Ceramide NP', 'Xanthophylls', 'Phytosphingosine', 'Phytosterols', 'Jojoba Esters', 'Physalis Pubescens Fruit Juice', 'Stearyl Glycyrrhetinate', 'Oryza Sativa (Rice) Bran Extract', 'Glycine Soja (Soybean) Oil', 'Carthamus Tinctorius Seed Oil', 'Palmitoyl Hexapeptide-12', 'Cetyl Palmitate', 'Trehalose', 'Lauric Acid', 'Sodium Hyaluronate Crosspolymer', 'Olea Europaea (Olive) Fruit Oil', 'Glucosamine Hcl', 'Tocopheryl Acetate', 'Coco-Caprylate/\u200bCaprate', 'Pisum Sativum (Pea) Extract', 'Tocopherol', 'Bambusa Vulgaris Leaf/\u200bStem Extract', 'Phenoxyethanol', 'Caprylyl Glycol', 'Carbomer', 'Trideceth-6 Phosphate', 'N-Hydroxysuccinimide', 'Ceteareth-20', 'Sodium Hydroxide', 'Laureth-23', 'Steareth-20', 'Propanediol', 'Chlorhexidine Digluconate', 'Polysorbate 20', 'Trisodium Ethylenediamine Disuccinate', 'Chlorphenesin', 'Potassium Sorbate', 'Ethylhexylglycerin']
--------------------------------------------------
Product: 1.0% | Night Switch Retinol 1%


            Lixir
Link: https://inkeedecoder.com/products/lixir-night-switch-retinol-1
Jumlah ingredient: 10
Ingredient: ['Aqua (Water)', 'Phospholipids', 'Leuconostoc/\u200bRadish Root Ferment Filtrate', 'Retinol 1.0%', 'Phenoxyethanol', 'Benzoic Acid', 'Glyceryl Laurate', 'EDTA', 'Dehydroacetic Acid', 'Ethylhexylglycerin']
--------------------------------------------------
Product: 1.0% | Retinol 1.0 Maximum Strength Refining Night Cream


            SkinCeuticals

Hal tersebut dilakukan untuk menambahkan kolom `ingredient` yang sebelumnya hanya terdapat 1 untuk setiap kelompok produk. 

Oleh karena itu, scraping data dilakukan agar kolom ingredient per product lebih lengkap dan detail.

Pada masalah kulit pori-pori besar atau pores. Setiap produk mempunyai jumlah yang ingredients yang bervariasi. Satu produk mempunyai sekitar 3 - 46 ingredients yang berbeda-beda.

##### Penyimpanan Data

In [5]:
df.to_csv("Skincare Dataset/pores_data.csv", index=False)

df.head(10)

,problem,ingredient,product name,product link
0,pores,"Propylene Glycol, PEG-75, PEG-8, Water, Salicy...",9.0% | Resist Bha 9\n \n\n P...,https://inkeedecoder.com/products/paulas-choic...
1,pores,"Salicylic Acid 6.0%, Resorcinol 2.0%, Phenol 1...",6.0% | Compound Salicylic Acid Liniment\n ...,https://inkeedecoder.com/products/sanyi-compou...
2,pores,"Aqua, Propylene Glycol, Azelaic Acid 15.0%, Te...",2.0% | Azelaic Acid Control Facial Acne Gel\n ...,https://inkeedecoder.com/products/aisuanis-emp...
3,pores,"Water, Poloxamer 407, Laureth-40, PEG-8, Glyce...",2.0% | Nuorishing Spa Mask\n \n\n ...,https://inkeedecoder.com/products/broda-r-pro-...
4,pores,"Aqua (Water), Propylene Glycol, Ammonium Polya...",2.0% | Flawless Neutralising Gel\n \n\n...,https://inkeedecoder.com/products/dr-sam-bunti...
5,pores,"Salicylic Acid 2.0%, Neem Oil (Anti-Bacterial)...",2.0% | Neem & BHA Spot Clarifying Serum\n ...,https://inkeedecoder.com/products/dr-sheths-ne...
6,pores,"Propanediol, Spring Water, Salicylic Acid 2.0%...",2.0% | Salicylic Acid 2% Serum\n \n\n ...,https://inkeedecoder.com/products/garden-of-wi...
7,pores,"Salicylic Acid 2.0%, Water (Aqua), Alcohol, Ha...",2.0% | Rapid Relief Acne Spot Treatment\n ...,https://inkeedecoder.com/products/murad-rapid-...
8,pores,"Salicylic Acid 2.0%, Water, Alcohol Denat, Ham...",2.0% | Clear Pore Oil-Eliminating Astringent\n...,https://inkeedecoder.com/products/neutrogena-c...
9,pores,"Water (Aqua), Dipropylene Glycol, Pentylene Gl...",2.0% | Clear Regular Strength Anti-Redness Exf...,https://inkeedecoder.com/products/paulas-choic...

Data yang sudah di scraping disimpan dan diperbarui ke dalam bentuk csv agar dapat di masukkan ke database supabase

Terlihat dari 10 hasil awal yang di tampilkan setiap produk memiliki ingredient yang berbeda-beda